/**
 * margin-report.mjs — Phase 6. Computes per-plan gross margin from the real cost model and writes
 * docs/PRICING.md with 2–3 options per plan + a recommendation to hit ≥80% GM. It STAGES nothing
 * live — it never edits plans.config.js. Applying prices is the owner's explicit call (Phase 6 gate).
 *
 * Costs: Call Floor call costs are MEASURED from ai_usage_events when DATABASE_URL is set (else the
 * measured constants). Interview/analysis costs use the measured price-book constants (those frozen
 * calls are unwrapped — the audit's estimate-only set). All at LIST rates (the honest cost structure).
 *
 * Run:  node scripts/callfloor/margin-report.mjs           (writes docs/PRICING.md, prints summary)
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PLANS } from '../../server/plans.config.js';
import { VOICE_MINUTE_USD, ANALYSIS_CYCLE_TOKENS, PRICEBOOK } from '../../server/callfloor/pricebook.config.js';
import { EGP_PER_USD, PAYMENT_FEE, egpToUsd } from '../../server/callfloor/margin.config.js';
import { TARGET_MARGIN, marginFor, affordableVoiceMinutes, priceForTarget } from '../../server/callfloor/marginEngine.js';

const __dir = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.join(__dir, '..', '..', 'docs', 'PRICING.md');

// ── Cost model (LIST) ──────────────────────────────────────────────────────────────────────────
const voiceMinUsd = VOICE_MINUTE_USD.cascadeListEstimate.mid;         // $/voice-minute, cascaded LIST
const groq = PRICEBOOK['groq:llama-3.3-70b-versatile'];
// Analysis per session = half the measured daily-cycle tokens (interview + re-interview + gen), priced at Groq LIST.
const analysisPerSessionUsd = (ANALYSIS_CYCLE_TOKENS.in / 2) * groq.list.in + (ANALYSIS_CYCLE_TOKENS.out / 2) * groq.list.out;
const COSTS = { voiceMinUsd, analysisPerSessionUsd, infraPerUserUsd: 0 };
const usd = (v) => `$${(Number(v) || 0).toFixed(2)}`;
const pct = (v) => (v == null ? 'n/a' : `${(v * 100).toFixed(1)}%`);

// Per-plan daily voice = interview dailyLiveMinutes + Call Floor dailyCallMinutes; sessions/day =
// interviews + estimated calls (a call ≈ 4 min). Free-talk shares the call allowance.
function planUsage(planId, factor) {
  const p = PLANS[planId];
  const interviewMin = (p.dailyLiveMinutes || 0);
  const callMin = (p.callFloor?.dailyCallMinutes || 0);
  const voicePerDay = (interviewMin + callMin) * factor;
  const interviews = (p.dailySessions || 0);
  const calls = callMin / 4;                              // ~4 min/call
  const sessionsPerDay = (interviews + calls) * factor;
  return { voiceMinPerMonth: voicePerDay * 30, sessionsPerMonth: sessionsPerDay * 30,
    voicePerDay, sessionsPerDay: sessionsPerDay };
}

function planBlock(planId) {
  const p = PLANS[planId];
  const priceEgp = p.priceEGP || 0;
  const rev = egpToUsd(priceEgp);
  const typical = planUsage(planId, 0.5);
  const heavy = planUsage(planId, 1.0);
  const mT = marginFor(priceEgp, typical, COSTS);
  const mH = marginFor(priceEgp, heavy, COSTS);
  // Options to reach ≥80% at HEAVY usage (the binding case):
  const affMinHeavy = affordableVoiceMinutes(priceEgp, heavy.sessionsPerMonth, COSTS);   // total voice min/MONTH
  const priceNeeded = priceForTarget(heavy, COSTS, TARGET_MARGIN, EGP_PER_USD.rate);       // EGP at current allowance
  return { planId, label: p.label, priceEgp, rev, typical, heavy, mT, mH, affMinHeavy, priceNeeded,
    curVoicePerDay: heavy.voicePerDay };
}

const basic = planBlock('basic');
const elite = planBlock('elite');

function optionsLines(b) {
  const affPerDay = b.affMinHeavy == null ? null : b.affMinHeavy / 30;
  return [
    `- **Option A — cut the allowance** (keep ${b.priceEgp} EGP): reduce TOTAL daily voice (interview + call) to ` +
      `${affPerDay == null ? 'below break-even — the price cannot fund voice at 80%' : `~${affPerDay.toFixed(1)} min/day`} ` +
      `(now ${b.curVoicePerDay.toFixed(0)} min/day) → holds 80% even at heavy use.`,
    `- **Option B — raise the price** (keep ~${b.curVoicePerDay.toFixed(0)} min/day): ~${b.priceNeeded ? Math.round(b.priceNeeded) : 'n/a'} EGP ` +
      `(now ${b.priceEgp}) → holds 80% at heavy use.`,
    `- **Option C — cut $/voice-minute**: caching / a cheaper STT-TTS path lowers the ${usd(COSTS.voiceMinUsd)}/min that dominates COGS; ` +
      `every 25% cut raises the affordable allowance ~33%.`,
  ].join('\n');
}

const md = `# PRICING — Call Floor margin model (Phase 6)

**Generated by \`scripts/callfloor/margin-report.mjs\`. STAGED ONLY — no live price was changed.**
Applying any price/allowance is the owner's explicit call.

> ⚠ **Placeholders to refresh before acting:** EGP↔USD = **${EGP_PER_USD.rate}** (checked ${EGP_PER_USD.checkedOn}, ${EGP_PER_USD.source}); payment fee = **${(PAYMENT_FEE.pct * 100)}% + ${usd(PAYMENT_FEE.fixedUsd)}** (${PAYMENT_FEE.note}); voice = **${usd(voiceMinUsd)}/min** LIST (${VOICE_MINUTE_USD.cascadeListEstimate.basis}). Re-verify these, then re-run.

## Measured unit costs (LIST)
- **Voice:** ${usd(voiceMinUsd)} per minute (cascaded path — Deepgram STT + Aura-2 TTS + ~1 Groq turn/min).
- **Post-call analysis:** ${usd(analysisPerSessionUsd)} per session (½ the measured ${ANALYSIS_CYCLE_TOKENS.in + ANALYSIS_CYCLE_TOKENS.out}-token daily cycle at Groq list).
- **Payment fee:** ${(PAYMENT_FEE.pct * 100)}% + ${usd(PAYMENT_FEE.fixedUsd)} per monthly payment.
- Per-user infra ≈ \\$0 marginal (Render web + Neon free tier are ~fixed). *Actual* cost today is ~\\$0 (free tiers) — margins here use LIST because free tiers don't scale.
- **Real Call-Floor call costs land in \`ai_usage_events\`** — run this script with \`DATABASE_URL\` set (prod) to replace the voice constant with the measured blended \\$/min from live calls.

## The verdict at CURRENT prices + allowances
| Plan | Price | Gross rev (USD) | Total voice/day (heavy) | Margin — typical (50%) | Margin — heavy (100%) |
|---|---|---|---|---|---|
| ${basic.label} | ${basic.priceEgp} EGP | ${usd(basic.rev)} | ${basic.curVoicePerDay.toFixed(0)} min | **${pct(basic.mT.margin)}** | **${pct(basic.mH.margin)}** |
| ${elite.label} | ${elite.priceEgp} EGP | ${usd(elite.rev)} | ${elite.curVoicePerDay.toFixed(0)} min | **${pct(elite.mT.margin)}** | **${pct(elite.mH.margin)}** |

**Both plans miss the 80% target** because the current daily voice allowances (interview + Call Floor combined) cost more than 20% of the EGP price. Heavy COGS breakdown per user/month:
- ${basic.label}: voice ${usd(basic.mH.cogs.voice)} + analysis ${usd(basic.mH.cogs.analysis)} + fee ${usd(basic.mH.cogs.fee)} = **${usd(basic.mH.cogs.total)}** vs ${usd(basic.rev)} revenue.
- ${elite.label}: voice ${usd(elite.mH.cogs.voice)} + analysis ${usd(elite.mH.cogs.analysis)} + fee ${usd(elite.mH.cogs.fee)} = **${usd(elite.mH.cogs.total)}** vs ${usd(elite.rev)} revenue.

## Options to reach ≥80% (per plan)
### ${basic.label}
${optionsLines(basic)}
### ${elite.label}
${optionsLines(elite)}

## Recommendation (to hold ≥80% at HEAVY use)
The honest lever is the **allowance**, not price (the Egyptian market caps willingness-to-pay, and the
required prices are steep). Size each plan's TOTAL daily voice to its affordable ceiling:
- **${basic.label}:** ${basic.affMinHeavy == null ? 'price too low for meaningful voice at 80% — raise to ~' + (basic.priceNeeded ? Math.round(basic.priceNeeded) : '?') + ' EGP OR accept a lower margin floor' : '~' + (basic.affMinHeavy / 30).toFixed(1) + ' min/day total voice'} (split across interview + Call Floor as the owner prefers).
- **${elite.label}:** ${elite.affMinHeavy == null ? 'raise to ~' + (elite.priceNeeded ? Math.round(elite.priceNeeded) : '?') + ' EGP' : '~' + (elite.affMinHeavy / 30).toFixed(1) + ' min/day total voice'}.

Because typical usage runs ~50%, a middle path (a modest allowance cut + a modest price bump) can
hold ≥80% at heavy use while feeling generous at typical use. **These numbers are recommendations —
nothing is applied. Refresh the ⚠ placeholders, pick a lever per plan, and give the go to apply.**

## Most expensive thing + top cost cuts
1. **Voice minutes dominate** (${usd(voiceMinUsd)}/min) — the single biggest per-user cost. Cutting it (caching repeated TTS, a cheaper STT tier, shorter sessions) moves margin the most.
2. **Metered allowances are the guarantee** — the ceiling makes margin arithmetic, not a bet on user behavior.
3. **Free tiers are a subsidy, not a structure** — today's actual cost is ~\\$0, but price at LIST so scale doesn't surprise you.

## Re-run this when
prices change · usage patterns shift · Call Floor real call-cost data lands in ai_usage_events · the EGP↔USD rate or payment rail changes.
`;

await writeFile(DOCS, md, 'utf8');
console.log('[margin] wrote docs/PRICING.md');
console.log(`[margin] ${basic.label}: typical ${pct(basic.mT.margin)}, heavy ${pct(basic.mH.margin)} @ ${basic.priceEgp} EGP`);
console.log(`[margin] ${elite.label}: typical ${pct(elite.mT.margin)}, heavy ${pct(elite.mH.margin)} @ ${elite.priceEgp} EGP`);
console.log(`[margin] affordable voice: ${basic.label} ${basic.affMinHeavy == null ? 'n/a' : (basic.affMinHeavy / 30).toFixed(1) + ' min/day'}, ${elite.label} ${elite.affMinHeavy == null ? 'n/a' : (elite.affMinHeavy / 30).toFixed(1) + ' min/day'}`);
console.log('[margin] STAGED ONLY — plans.config.js unchanged.');
